[tool.poetry]
name = "gda20"
version = "0.1.0"
description = "cartographic tools for working with the MGA & GDA20"
authors = ["Sam <chompar4@gmail.com>"]

[tool.poetry.dependencies]
geomag = "^0.9.2015"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.2"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
