[tool.poetry]
name = "gda20"
version = "0.1.0"
description = "cartographic tools for working with the MGA & GDA20"
authors = ["Sam <chompar4@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8.2"
pytest = "^5.4.3"
numpy = "^1.19.0"
isort = "^5.1.2"
black = "^19.10b0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.2"
flake8 = "^3.7.9"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
